# 1. 데이터셋의 루트 폴더 경로를 지정합니다.
# Roboflow의 경로('../train/images') 대신, 우리 프로젝트 구조를 사용합니다.
path: ../data

# 2. train/val/test 이미지 폴더 경로를 지정합니다.
train: images/train
val: images/val
test: images/test

# 3. Roboflow 데이터셋에 포함된 10개의 클래스 이름을 순서대로 모두 적어줍니다.
names:
  0: Garlic
  1: onion