# Hydra가 실행되는 위치(outputs/...)에서 두 단계 위인 프로젝트 루트 폴더로 이동합니다.
path: ../../

train: data/image/train
val: data/image/val    
test: data/image/test

# Roboflow에서 가져온 데이터셋의 클래스 정보를 사용합니다.
nc: 2
names: ['Garlic', 'onion']